apiVersion: apps/v1
kind: Deployment
metadata:
  name: clinic-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clinic-frontend
  template:
    metadata:
      labels:
        app: clinic-frontend
    spec:
      containers:
        - name: clinic-frontend
          # This matches the image you just built
          image: 5122771/clinic-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: clinic-frontend-service
spec:
  selector:
    app: clinic-frontend
  type: NodePort
  ports:
    - protocol: TCP
      port: 80        # The port Nginx listens on inside the container
      targetPort: 80
      nodePort: 30005 # You will access the app at http://localhost:30005